import type { WorkflowReference } from '../../shared/reference'

export const WORKFLOW_REFERENCES: WorkflowReference[] = [
  {
    id: 'status',
    displayName: 'Status',
    category: 'inspection',
    purpose: 'Inspect repository health without fetching or changing it.',
    aliases: ['status', 'status please'],
    runner: 'scripts/tctbp-run-status.js --no-fetch',
    dryRun: true,
    branchRestriction: 'Any branch or detached state.',
    preconditions: ['Repository metadata must be readable.'],
    localEffects: ['Collects local and tracking-ref observations.'],
    remoteEffects: [],
    nonEffects: ['No fetch, commit, push, merge, tag or deployment.'],
    relatedWorkflows: ['checkpoint', 'resume', 'publish'],
    guardrailIds: [],
  },
  {
    id: 'checkpoint',
    displayName: 'Checkpoint',
    category: 'preservation',
    purpose: 'Preserve current work in a local commit.',
    aliases: ['checkpoint', 'checkpoint please'],
    runner: 'scripts/tctbp-run-checkpoint.js',
    dryRun: false,
    branchRestriction: 'Attached working branch.',
    preconditions: ['No unresolved Git operation or index conflicts.'],
    localEffects: ['Creates a local checkpoint commit.'],
    remoteEffects: [],
    nonEffects: ['Does not push, merge, tag, version or deploy.'],
    relatedWorkflows: ['status', 'publish', 'handover'],
    guardrailIds: [
      'git.operation.active',
      'git.head.detached',
      'git.branch.diverged',
    ],
  },
  {
    id: 'publish',
    displayName: 'Publish',
    category: 'preservation',
    purpose: 'Publish the current branch to its configured origin.',
    aliases: ['publish', 'publish please'],
    runner: 'scripts/tctbp-run-publish.js',
    dryRun: false,
    branchRestriction: 'Attached, non-diverged branch.',
    preconditions: ['Working tree is preserved.', 'Branch is not behind.'],
    localEffects: ['May establish upstream tracking.'],
    remoteEffects: ['Pushes the current branch.'],
    nonEffects: ['Does not merge, tag, version, deploy or ship.'],
    relatedWorkflows: ['checkpoint', 'handover', 'promote'],
    guardrailIds: [
      'git.operation.active',
      'git.head.detached',
      'git.branch.behind',
      'git.branch.diverged',
    ],
  },
  {
    id: 'handover',
    displayName: 'Handover',
    category: 'continuation',
    purpose: 'Safely continue current work on another machine.',
    aliases: ['handover', 'handover please', 'handover local'],
    runner: 'scripts/tctbp-run-handover.js',
    dryRun: false,
    branchRestriction: 'Attached, safely reconcilable work branch.',
    preconditions: ['Repository can be preserved and published safely.'],
    localEffects: ['Preserves work and records continuation context.'],
    remoteEffects: ['Publishes the continuation baseline.'],
    nonEffects: ['Does not promote, deploy or ship.'],
    relatedWorkflows: ['resume', 'checkpoint', 'publish'],
    guardrailIds: [
      'git.operation.active',
      'git.head.detached',
      'git.branch.diverged',
      'git.working-tree.dirty-behind',
    ],
  },
  {
    id: 'resume',
    displayName: 'Resume',
    category: 'continuation',
    purpose: 'Restore a safe local baseline after changing machines.',
    aliases: ['resume', 'resume please'],
    runner: 'scripts/tctbp-run-resume.js',
    dryRun: false,
    branchRestriction: 'Clean attached branch.',
    preconditions: ['Working tree is clean.', 'Tracking evidence is usable.'],
    localEffects: ['Reconciles the local branch with origin safely.'],
    remoteEffects: [],
    nonEffects: ['Does not discard dirty work or resolve divergence.'],
    relatedWorkflows: ['handover', 'status'],
    guardrailIds: [
      'git.working-tree.dirty',
      'git.branch.diverged',
    ],
  },
  {
    id: 'promote',
    displayName: 'Promote',
    category: 'environment',
    purpose: 'Merge explicitly between configured environment roles.',
    aliases: [
      'promote staging',
      'promote review',
      'promote production',
      'promote prod',
    ],
    runner: 'scripts/tctbp-run-promote.js <target>',
    dryRun: false,
    branchRestriction: 'Configured source environment branch.',
    preconditions: ['Source branch is clean, published and gate-ready.'],
    localEffects: ['Merges into the selected environment branch.'],
    remoteEffects: ['Publishes the promoted environment branch.'],
    nonEffects: ['Does not deploy or ship automatically.'],
    relatedWorkflows: ['publish', 'deploy', 'ship'],
    guardrailIds: [
      'git.operation.active',
      'git.branch.behind',
      'git.branch.diverged',
    ],
  },
  {
    id: 'deploy',
    displayName: 'Deploy',
    category: 'environment',
    purpose: 'Deploy one explicit environment from its mapped branch.',
    aliases: [
      'deploy dev',
      'deploy staging',
      'deploy prod',
      'deploy production',
    ],
    runner: 'scripts/tctbp-run-deploy.js <environment>',
    dryRun: false,
    branchRestriction: 'Branch mapped to the selected environment.',
    preconditions: ['Deployment is enabled and its gates pass.'],
    localEffects: ['Runs configured local deployment preparation.'],
    remoteEffects: ['Updates the selected runtime environment.'],
    nonEffects: ['Does not promote, version or ship automatically.'],
    relatedWorkflows: ['promote', 'ship'],
    guardrailIds: ['git.operation.active', 'git.branch.diverged'],
  },
  {
    id: 'ship',
    displayName: 'Ship',
    category: 'environment',
    purpose: 'Run the explicit production release workflow.',
    aliases: ['ship', 'ship please', 'shipping'],
    runner: 'scripts/tctbp-run-ship.js',
    dryRun: false,
    branchRestriction: 'Configured production branch.',
    preconditions: ['Release gates and branch/version alignment pass.'],
    localEffects: ['Creates release version and tag state.'],
    remoteEffects: ['Publishes the production release and tags.'],
    nonEffects: ['Does not deploy production automatically.'],
    relatedWorkflows: ['promote', 'deploy'],
    guardrailIds: [
      'git.operation.active',
      'git.branch.behind',
      'git.branch.diverged',
    ],
  },
  {
    id: 'abort',
    displayName: 'Abort inspection',
    category: 'continuation',
    purpose: 'Diagnose an interrupted workflow before recovery.',
    aliases: ['abort'],
    runner: 'scripts/tctbp-run-abort.js --dry-run',
    dryRun: true,
    branchRestriction: 'Repository with partial workflow state.',
    preconditions: ['An interrupted operation needs diagnosis.'],
    localEffects: ['Reports recovery options in dry-run mode.'],
    remoteEffects: [],
    nonEffects: ['Does not discard work or mutate Git in dry-run mode.'],
    relatedWorkflows: ['status', 'resume'],
    guardrailIds: [],
  },
  {
    id: 'branch',
    displayName: 'Branch',
    category: 'continuation',
    purpose: 'Create or switch work using the configured branch policy.',
    aliases: ['branch'],
    runner: 'scripts/tctbp-run-branch.js',
    dryRun: false,
    branchRestriction: 'Configured working branch model.',
    preconditions: ['Current work is safely preserved.'],
    localEffects: ['Creates or switches a local work branch.'],
    remoteEffects: [],
    nonEffects: ['Does not publish, promote or deploy automatically.'],
    relatedWorkflows: ['checkpoint', 'publish'],
    guardrailIds: [
      'git.operation.active',
      'git.working-tree.dirty',
    ],
  },
]
