import type { WorkflowReference } from '../../shared/reference'

export const WORKFLOW_REFERENCES: WorkflowReference[] = [
  {
    id: 'status',
    displayName: 'Status',
    category: 'inspection',
    purpose: 'Inspect repository health without fetching or changing it.',
    chatInvokable: true,
    aliases: ['status', 'status please'],
    runner: 'scripts/tctbp-run-status.js --no-fetch',
    dryRun: true,
    branchRestriction: 'Any branch or detached state.',
    preconditions: ['Repository metadata must be readable.'],
    localEffects: ['Collects local and tracking-ref observations.'],
    remoteEffects: [],
    nonEffects: ['No fetch, commit, push, merge, tag or deployment.'],
    relatedWorkflows: ['checkpoint', 'resume', 'publish'],
    guardrailIds: [],
  },
  {
    id: 'checkpoint',
    displayName: 'Checkpoint',
    category: 'preservation',
    purpose: 'Preserve current work in a local commit.',
    chatInvokable: true,
    aliases: ['checkpoint', 'checkpoint please'],
    runner: 'scripts/tctbp-run-checkpoint.js',
    dryRun: false,
    branchRestriction: 'Attached working branch.',
    preconditions: ['No unresolved Git operation or index conflicts.'],
    localEffects: ['Creates a local checkpoint commit.'],
    remoteEffects: [],
    nonEffects: ['Does not push, merge, tag, version or deploy.'],
    relatedWorkflows: ['status', 'publish', 'handover'],
    guardrailIds: [
      'git.operation.active',
      'git.head.detached',
      'git.branch.diverged',
    ],
  },
  {
    id: 'publish',
    displayName: 'Publish',
    category: 'preservation',
    purpose: 'Publish the current branch to its configured origin.',
    chatInvokable: true,
    aliases: ['publish', 'publish please'],
    runner: 'scripts/tctbp-run-publish.js',
    dryRun: false,
    branchRestriction: 'Attached, non-diverged branch.',
    preconditions: ['Working tree is preserved.', 'Branch is not behind.'],
    localEffects: ['May establish upstream tracking.'],
    remoteEffects: ['Pushes the current branch.'],
    nonEffects: ['Does not merge, tag, version, deploy or ship.'],
    relatedWorkflows: ['checkpoint', 'handover', 'promote'],
    guardrailIds: [
      'git.operation.active',
      'git.head.detached',
      'git.branch.behind',
      'git.branch.diverged',
    ],
  },
  {
    id: 'handover',
    displayName: 'Handover',
    category: 'continuation',
    purpose: 'Safely continue current work on another machine.',
    chatInvokable: true,
    aliases: ['handover', 'handover please', 'handover local'],
    runner: 'scripts/tctbp-run-handover.js',
    dryRun: false,
    branchRestriction: 'Attached, safely reconcilable work branch.',
    preconditions: ['Repository can be preserved and published safely.'],
    localEffects: ['Preserves work and records continuation context.'],
    remoteEffects: ['Publishes the continuation baseline.'],
    nonEffects: ['Does not promote, deploy or ship.'],
    relatedWorkflows: ['resume', 'checkpoint', 'publish'],
    guardrailIds: [
      'git.operation.active',
      'git.head.detached',
      'git.branch.diverged',
      'git.working-tree.dirty-behind',
    ],
  },
  {
    id: 'resume',
    displayName: 'Resume',
    category: 'continuation',
    purpose: 'Restore a safe local baseline after changing machines.',
    chatInvokable: true,
    aliases: ['resume', 'resume please'],
    runner: 'scripts/tctbp-run-resume.js',
    dryRun: false,
    branchRestriction: 'Clean attached branch.',
    preconditions: ['Working tree is clean.', 'Tracking evidence is usable.'],
    localEffects: ['Reconciles the local branch with origin safely.'],
    remoteEffects: [],
    nonEffects: ['Does not discard dirty work or resolve divergence.'],
    relatedWorkflows: ['handover', 'status'],
    guardrailIds: [
      'git.working-tree.dirty',
      'git.branch.diverged',
    ],
  },
  {
    id: 'promote',
    displayName: 'Promote',
    category: 'environment',
    purpose: 'Merge explicitly between configured environment roles.',
    chatInvokable: true,
    aliases: [
      'promote staging',
      'promote review',
      'promote production',
      'promote prod',
    ],
    runner: 'scripts/tctbp-run-promote.js <target>',
    dryRun: false,
    branchRestriction: 'Configured source environment branch.',
    preconditions: ['Source branch is clean, published and gate-ready.'],
    localEffects: ['Merges into the selected environment branch.'],
    remoteEffects: ['Publishes the promoted environment branch.'],
    nonEffects: ['Does not deploy or ship automatically.'],
    relatedWorkflows: ['publish', 'deploy', 'ship'],
    guardrailIds: [
      'git.operation.active',
      'git.branch.behind',
      'git.branch.diverged',
    ],
  },
  {
    id: 'deploy',
    displayName: 'Deploy',
    category: 'environment',
    purpose: 'Deploy one explicit environment from its mapped branch.',
    chatInvokable: true,
    aliases: [
      'deploy dev',
      'deploy staging',
      'deploy prod',
      'deploy production',
    ],
    runner: 'scripts/tctbp-run-deploy.js <environment>',
    dryRun: false,
    branchRestriction: 'Branch mapped to the selected environment.',
    preconditions: ['Deployment is enabled and its gates pass.'],
    localEffects: ['Runs configured local deployment preparation.'],
    remoteEffects: ['Updates the selected runtime environment.'],
    nonEffects: ['Does not promote, version or ship automatically.'],
    relatedWorkflows: ['promote', 'ship'],
    guardrailIds: ['git.operation.active', 'git.branch.diverged'],
  },
  {
    id: 'ship',
    displayName: 'Ship',
    category: 'environment',
    purpose: 'Run the explicit production release workflow.',
    chatInvokable: true,
    aliases: ['ship', 'ship please', 'shipping'],
    runner: 'scripts/tctbp-run-ship.js',
    dryRun: false,
    branchRestriction: 'Configured production branch.',
    preconditions: ['Release gates and branch/version alignment pass.'],
    localEffects: ['Creates release version and tag state.'],
    remoteEffects: ['Publishes the production release and tags.'],
    nonEffects: ['Does not deploy production automatically.'],
    relatedWorkflows: ['promote', 'deploy'],
    guardrailIds: [
      'git.operation.active',
      'git.branch.behind',
      'git.branch.diverged',
    ],
  },
  {
    id: 'abort',
    displayName: 'Abort inspection',
    category: 'continuation',
    purpose: 'Diagnose an interrupted workflow before recovery.',
    chatInvokable: true,
    aliases: ['abort'],
    runner: 'scripts/tctbp-run-abort.js --dry-run',
    dryRun: true,
    branchRestriction: 'Repository with partial workflow state.',
    preconditions: ['An interrupted operation needs diagnosis.'],
    localEffects: ['Reports recovery options in dry-run mode.'],
    remoteEffects: [],
    nonEffects: ['Does not discard work or mutate Git in dry-run mode.'],
    relatedWorkflows: ['status', 'resume'],
    guardrailIds: [],
  },
  {
    id: 'branch',
    displayName: 'Branch',
    category: 'continuation',
    purpose: 'Create or switch work using the configured branch policy.',
    chatInvokable: true,
    aliases: ['branch'],
    runner: 'scripts/tctbp-run-branch.js',
    dryRun: false,
    branchRestriction: 'Configured working branch model.',
    preconditions: ['Current work is safely preserved.'],
    localEffects: ['Creates or switches a local work branch.'],
    remoteEffects: [],
    nonEffects: ['Does not publish, promote or deploy automatically.'],
    relatedWorkflows: ['checkpoint', 'publish'],
    guardrailIds: [
      'git.operation.active',
      'git.working-tree.dirty',
    ],
  },
  {
    id: 'preflight',
    displayName: 'Preflight',
    category: 'inspection',
    purpose: 'Verify the working state non-mutatively before advancing.',
    chatInvokable: true,
    aliases: ['preflight', 'preflight please'],
    runner: 'scripts/tctbp-run-preflight.js',
    dryRun: true,
    branchRestriction: 'Any attached branch; inspects uncommitted state.',
    preconditions: ['Repository metadata must be readable.'],
    localEffects: ['Runs configured quality gates and inspects working state.'],
    remoteEffects: [],
    nonEffects: ['Does not commit, push, tag, merge, switch, deploy or bump versions.'],
    relatedWorkflows: ['status', 'checkpoint', 'publish'],
    guardrailIds: ['git.operation.active', 'git.head.detached'],
  },
  {
    id: 'orient',
    displayName: 'Orient',
    category: 'inspection',
    purpose: 'Load the current repository and continuation context.',
    chatInvokable: true,
    aliases: ['orient', 'orient please'],
    runner: 'scripts/tctbp-run-orient.js',
    dryRun: true,
    branchRestriction: 'Any repository state.',
    preconditions: ['Repository metadata must be readable.'],
    localEffects: ['Reports branch, sync, and continuation state.'],
    remoteEffects: [],
    nonEffects: ['Does not fetch, mutate, publish or switch branches.'],
    relatedWorkflows: ['status', 'resume'],
    guardrailIds: [],
  },
  {
    id: 'release',
    displayName: 'Release',
    category: 'environment',
    purpose: 'Orchestrate the complete environment pipeline with a journal.',
    chatInvokable: true,
    aliases: ['release', 'release please', 'prepare release', 'prepare release please'],
    runner: 'scripts/tctbp-run-release.js',
    dryRun: false,
    branchRestriction: 'Configured environment pipeline branches.',
    preconditions: ['Each pipeline stage passes its gates and candidate checks.'],
    localEffects: ['Records atomic release journal evidence per stage.'],
    remoteEffects: ['Publishes promoted and shipped stages.'],
    nonEffects: ['Does not run project-specific deploy mechanics itself.'],
    relatedWorkflows: ['deploy', 'promote', 'ship'],
    guardrailIds: ['git.operation.active', 'git.branch.behind', 'git.branch.diverged'],
  },
  {
    id: 'hotfix',
    displayName: 'Hotfix',
    category: 'environment',
    purpose: 'Ship an emergency production fix outside the normal chain.',
    chatInvokable: true,
    aliases: ['hotfix', 'hotfix start', 'hotfix finish', 'emergency fix'],
    runner: 'scripts/tctbp-run-hotfix.js {start|finish}',
    dryRun: false,
    branchRestriction: 'Production branch to start; hotfix/* to finish.',
    preconditions: ['Hotfix branch exists and is clean when finishing.'],
    localEffects: ['Creates or merges the hotfix branch.'],
    remoteEffects: ['Ships a patch release and backports main.'],
    nonEffects: ['Does not promote through the normal review chain.'],
    relatedWorkflows: ['ship', 'publish'],
    guardrailIds: ['git.operation.active', 'git.branch.diverged'],
  },
  {
    id: 'gate',
    displayName: 'Gate',
    category: 'inspection',
    purpose: 'Run one targeted quality gate (test, lint, or build).',
    chatInvokable: false,
    aliases: ['run tests', 'run lint', 'run build', 'gate test', 'gate lint', 'gate build'],
    runner: 'scripts/tctbp-run-gate.js <test|lint|build>',
    dryRun: true,
    branchRestriction: 'Any attached branch.',
    preconditions: ['A configured command exists for the requested gate.'],
    localEffects: ['Runs the configured gate command.'],
    remoteEffects: [],
    nonEffects: ['Does not commit, push, merge, tag or deploy.'],
    relatedWorkflows: ['preflight', 'ship'],
    guardrailIds: ['git.operation.active'],
  },
  {
    id: 'version',
    displayName: 'Version',
    category: 'inspection',
    purpose: 'Report branch, version and tag alignment.',
    chatInvokable: true,
    aliases: ['version status', 'version check'],
    runner: 'scripts/tctbp-run-version.js',
    dryRun: true,
    branchRestriction: 'Any attached branch.',
    preconditions: ['Version sources are readable.'],
    localEffects: ['Reports version source alignment.'],
    remoteEffects: [],
    nonEffects: ['Does not bump versions, tag, commit or push.'],
    relatedWorkflows: ['ship', 'status'],
    guardrailIds: [],
  },
  {
    id: 'rollback',
    displayName: 'Rollback',
    category: 'continuation',
    purpose: 'Revert the latest checkpoint commit safely.',
    chatInvokable: true,
    aliases: ['rollback', 'revert last checkpoint'],
    runner: 'scripts/tctbp-run-rollback.js',
    dryRun: true,
    branchRestriction: 'Attached branch with a checkpoint to revert.',
    preconditions: ['Preview runs by default; explicit apply is required.'],
    localEffects: ['Reverses the latest checkpoint via git revert.'],
    remoteEffects: [],
    nonEffects: ['Does not rewrite history or discard dirty work.'],
    relatedWorkflows: ['checkpoint', 'resume'],
    guardrailIds: ['git.operation.active'],
  },
  {
    id: 'ticket',
    displayName: 'Ticket',
    category: 'administration',
    purpose: 'Create, report, and triage deterministic tickets.',
    chatInvokable: true,
    aliases: ['ticket create', 'ticket report', 'ticket triage'],
    runner: 'scripts/tctbp-run-ticket.js <create|report|triage>',
    dryRun: true,
    branchRestriction: 'Any attached branch.',
    preconditions: ['Ticket creation previews by default and needs explicit apply.'],
    localEffects: ['Writes ticket entries when explicitly applied.'],
    remoteEffects: [],
    nonEffects: ['Does not commit, push, merge or deploy.'],
    relatedWorkflows: ['status', 'checkpoint'],
    guardrailIds: [],
  },
  {
    id: 'scaffold',
    displayName: 'Scaffold',
    category: 'administration',
    purpose: 'Create a new TCTBP-enabled project from scratch.',
    chatInvokable: true,
    aliases: ['scaffold', 'scaffold web', 'new project', 'create project'],
    runner: 'scripts/tctbp-run-scaffold.js',
    dryRun: true,
    branchRestriction: 'A new target path; scaffold rejects populated targets.',
    preconditions: ['The target path is empty and interview answers are valid.'],
    localEffects: ['Writes a full project skeleton with the TCTBP surface.'],
    remoteEffects: ['Optionally creates and pushes a remote after approval.'],
    nonEffects: ['Does not modify an existing populated repository.'],
    relatedWorkflows: ['status', 'checkpoint'],
    guardrailIds: [],
  },
]
